server:
  port: ${SERVER_PORT:8083}

coffee:
  service:
    base-url: ${COFFEE_SERVICE_URL:lb://coffee}

auth:
  service:
    base-url: ${AUTH_SERVICE_URL:lb://auth}

app:
  frontend:
    invitationPath: /invitation
    resetPswPath: /resetPassword
    company: Paga-Tu
    domainUrl: ${DOMAIN_URL:http://localhost:8888}

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  application:
    name: mail
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}

  # NATS Configuration
  nats:
    subject:
      next-payment: next-payment
      skip-payment: skip-payment
      invitation: invitation
      reset-password-mail: reset-password-mail
    server: ${NATS_SERVER:nats://localhost:4222}
    connection-timeout: 5000
    max-reconnect: -1
    connection-name: mail-service
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method